// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf9lQ9njZ9x5xH510sgTrp6TlXJ5pHelg',
    appId: '1:581867410538:web:288b4340281f6bb60ea613',
    messagingSenderId: '581867410538',
    projectId: 'mindsarthi-ae32b',
    authDomain: 'mindsarthi-ae32b.firebaseapp.com',
    storageBucket: 'mindsarthi-ae32b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8Ylau9K4OgQjF_C4pMcyYrHt5hSDtkXc',
    appId: '1:581867410538:android:723a27d51a67e5230ea613',
    messagingSenderId: '581867410538',
    projectId: 'mindsarthi-ae32b',
    storageBucket: 'mindsarthi-ae32b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC186RdtXGUZYWeb6lFfxZa4AtoOFQLWZw',
    appId: '1:581867410538:ios:ae1b0c1eef69cc360ea613',
    messagingSenderId: '581867410538',
    projectId: 'mindsarthi-ae32b',
    storageBucket: 'mindsarthi-ae32b.firebasestorage.app',
    iosBundleId: 'com.example.mindsarthi',
  );
}
